package im.cave.ms.network.packet.opcode;

public enum RecvOpcode {
    CUSTOM_LOGIN(0x7777),
    // Login Server
    BEFORE_LOGIN(0x67),
    SDO_LOGIN_REQUEST(0x69),
    SERVERSTATUS_REQUEST(0x6A),
    CHARLIST_REQUEST(0x6B),
    CHAR_SELECTED(0x72),
    CHECK_CHAR_NAME_REQUEST(0x77),
    SERVERLIST_REQUEST2(0x75),
    CREATE_CHAR_REQUEST(0x80),
    DELETE_CHAR(0x84),
    CANCEL_DELETE_CHAR(0x86),
    PONG(0x9C),
    ERROR_PACKET(0x9F),
    CLIENT_AUTH_REQUEST(0xA2),
    OPEN_CREATE_CHAR_LAYOUT(0XCF),
    //Channel Server
    UNK1(0x66),
    USER_ENTER_SERVER(0x71),
    CPONG(0x9D),
    USER_CASH_POINT_REQUEST(0xC5),
    USER_SLOT_EXPAND_REQUEST(0xC6),
    USER_TRANSFER_FIELD_REQUEST(0xCB),
    USER_TRANSFER_CHANNEL_REQUEST(0xCC),
    MIGRATE_TO_CASH_SHOP_REQUEST(0xD0),
    PLAYER_MOVE(0XD6),
    USER_SIT_REQUEST(0xD7),
    USER_PORTABLE_CHAIR_SIT_REQUEST(0xD8),
    CLOSE_RANGE_ATTACK(0xDB),
    RANGED_ATTACK(0xDC),
    MAGIC_ATTACK(0xDD),
    PLAYER_BODY_ATTACK(0xDE),
    USER_AREA_DOT_ATTACK(0xDF),
    USER_MOVING_SHOOT_ATTACK_PREPARE(0xE0),
    USER_ATTACK_USER(0xE1),
    CHAR_HIT(0xE2),
    GENERAL_CHAT(0xE4),
    CHAR_EMOTION(0xE7),
    USER_ACTIVATE_NICK_ITEM(0xEB),
    USER_ACTIVATE_DAMAGE_SKIN(0xEC),
    USER_ACTIVATE_DAMAGE_SKIN__PREMIUM(0xED),
    USER_ACTIVATE_DAMAGE_SKIN_PREMIUM(0xEE),
    USER_DAMAGE_SKIN_SAVE_REQUEST(0xF0),
    USER_SELECT_NPC(0xF7),
    USER_SCRIPT_MESSAGE_ANSWER(0xF8),
    USER_SHOP_REQUEST(0xF9),
    TRUNK_OPERATION(0xFA),
    USER_GATHER_ITEM_REQUEST(0x107),
    USER_SORT_ITEM_REQUEST(0x108),
    USER_CHANGE_SLOT_POSITION_REQUEST(0x109),
    USER_STAT_CHANGE_ITEM_USE_REQUEST(0x10E),
    USER_STAT_CHANGE_ITEM_CANCEL_REQUEST(0x10F),
    USER_SCRIPT_ITEM_USE_REQUEST(0x114),
    USER_RECIPE_OPEN_ITEM_USE_REQUEST(0x115),
    USER_CONSUME_CASH_ITEM_USE_REQUEST(0x116),
    PET_AUTO_EAT_FOOD(0x119),
    USER_PORTAL_SCROLL_USE_REQUEST(0x127),
    USER_FIELD_TRANSFER_REQUEST(0x128),
    USER_UPGRADE_ITEM_USE_REQUEST(0x129),
    USER_FLAME_ITEM_USE_REQUEST(0x12C),
    USER_ITEM_OPTION_UPGRADE_ITEM_USE_REQUEST(0x131),
    USER_ADDITIONAL_OPT_UPGRADE_ITEM_USE_REQUEST(0x132),
    EQUIP_ENCHANT_REQUEST(0x139),
    USER_ITEM_RELEASE_REQUEST(0x13F),
    USER_ABILITY_UP_REQUEST(0x148),
    USER_ABILITY_MASS_UP_REQUEST(0x149),
    CHANGE_STAT_REQUEST(0x14b),
    USER_SKILL_UP_REQUEST(0x150),
    USER_SKILL_USE_REQUEST(0x151),
    USER_SKILL_CANCEL_REQUEST(0x153),
    USER_ADD_FAME_REQUEST(0x159),
    CHAR_INFO_REQUEST(0x15c),
    PORTAL_SPECIAL(0x160),
    USER_QUEST_REQUEST(0x169),
    USER_LOTTERY_ITEM_USE_REQUEST(0x173),
    USER_REQUEST_INSTANCE_TABLE(0x180),
    USER_REQUEST_CHARACTER_POTENTIAL_SKILL_RAND_SET_UI(0X193),
    MINI_ROOM(0x1B3),
    PARTY_REQUEST(0x1B5),
    PARTY_INVITE_RESPONSE(0x1B6),
    CHANGE_KEYMAP(0x1D4),
    USER_HYPER_SKILL_UP_REQUEST(0x209),
    USER_HYPER_SKILL_RESET_REQUEST(0x20A),
    USER_HYPER_STAT_UP_REQUEST(0x20B),
    USER_HYPER_STAT_RESET_REQUEST(0x20C),
    CHANGE_CHAR_REQUEST(0x21B),
    COMBO_KILL_CHECK(0x233),
    SUMMON_MOVE(0x291),
    CHANGE_QUICKSLOT(0x2AE),
    UPDATE_TICK(0x330),
    SIGN_IN(0x34A),
    SKILL_COMMAND_LOCK(0x34D),
    UNITY_PORTAL_REQUEST(0x355),
    USER_OPEN_MYSTERY_EGG(0x3E8),
    WORLD_MAP_TRANSFER(0x3F1),
    OPEN_WORLD_MAP(0x3F9),
    MOB_MOVE(0x424),
    NPC_ANIMATION(0x44a),
    PICK_UP_ITEM(0x450),
    AFTER_CHANGE_MAP(0x45F),
    QUICK_MOVE_SELECT(0x48D),
    CASH_SHOP_POINT_REQUEST(0x5B7),
    CASH_SHOP_CASH_ITEM_REQUEST(0x5B8),
    BATTLE_ANALYSIS(0x5E2),
    EQUIP_EFFECT_OPT(0x60A),

    // OPCODE ENCRYPT BEGIN
    BEGIN(0xCA),
    //OPCODE ENCRYPT END
    END(0xA7F);

    private final int code;

    RecvOpcode(int code) {
        this.code = code;
    }

    public int getValue() {
        return code;
    }

    public static RecvOpcode getOpcode(int op) {
        for (RecvOpcode inHeader : RecvOpcode.values()) {
            if (inHeader.getValue() == op) {
                return inHeader;
            }
        }
        return null;
    }

}
