package im.cave.ms.connection.packet.opcode;

public enum RecvOpcode {
    CUSTOM_LOGIN(0x7777),

    UNK66(0x66),
    PERMISSION_REQUEST(0x67),
    SDO_LOGIN_REQUEST(0x69),
    SERVERSTATUS_REQUEST(0x6A),
    CHARLIST_REQUEST(0x6B),
    CLIENT_LOAD_DONE(0x6E),
    USER_ENTER_SERVER(0x71),
    CHAR_SELECTED(0x72),
    SERVERLIST_REQUEST2(0x74),
    CHECK_CHAR_NAME_REQUEST(0x75),
    RETURN_SELECT_WORLD_LAYOUT(0x76),
    CREATE_CHAR_REQUEST(0x7E),
    DELETE_CHAR(0x82),
    DELETE_CHAR_CONFIRM(0x83),
    CANCEL_DELETE_CHAR(0x84),
    TOS_ACCEPT_RESULT(0xB9),
    USER_LOGOUT(0x92),
    PONG(0x99),
    C_PONG(0x9A),
    ERROR_PACKET(0x9C),
    SHARE_INFORMATION_RESULT(0x9E),
    CLIENT_START(0x9F),
    CLIENT_ERROR(0xA2),
    SET_BURNING_CHAR(0XA7),
    AFTER_CREATE_CHAR(0xA8),
    ORDER_CHARACTERS(0xA9),
    SET_TOS(0xB9),
    SET_ACCOUNT_GENDER(0xBA),
    USER_CASH_POINT_REQUEST(0xC2),
    USER_SLOT_EXPAND_REQUEST(0xC3),

    BEGIN(0xCA),
    USER_TRANSFER_FIELD_REQUEST(0xCB),
    USER_TRANSFER_CHANNEL_REQUEST(0xCC),
    LP_OPEN_CREATE_CHAR_LAYOUT(0XCC),
    USER_TRANSFER_TO_HUB_REQUEST(0xCD),
    WORLD_TRANSFER_REQUEST(0xCE),
    WORLD_TRANSFER_SHINNING_STAR_REQUEST(0xCF),
    MIGRATE_TO_CASH_SHOP_REQUEST(0xD0),
    MIGRATE_TO_AUCTION_REQUEST(0xD1),
    //
    //
    //
    //
    PLAYER_MOVE(0XD6),
    USER_SIT_REQUEST(0xD7),
    USER_PORTABLE_CHAIR_SIT_REQUEST(0xD8),
    USER_EMOTICON_ITEM_USE_REQUEST(0xD9),
    USER_DANCE_STOP_REQUEST(0xDA),
    USER_MELEE_ATTACK(0xDB),
    USER_SHOOT_ATTACK(0xDC),
    USER_MAGIC_ATTACK(0xDD),
    USER_BODY_ATTACK(0xDE),
    USER_AREA_DOT_ATTACK(0xDF),
    USER_MOVING_SHOOT_ATTACK_PREPARE(0xE0),
    USER_ATTACK_USER(0xE1),
    CHAR_HIT(0xE2),
    GENERAL_CHAT(0xE4),
    USER_A_D_BOARD_CLOSE(0xE5),
    UNK_E6(0xE6),
    CHAR_EMOTION(0xE7),
    ANDROID_EMOTION(0xE8),
    USER_ACTIVATE_EFFECT_ITEM(0xE9),
    USER_MONKEY_EFFECT_ITEM(0xEA),
    USER_ACTIVATE_NICK_ITEM(0xEB),
    USER_ACTIVATE_DAMAGE_SKIN(0xEC),
    USER_ACTIVATE_DAMAGE_SKIN__PREMIUM(0xED),
    USER_ACTIVATE_DAMAGE_SKIN_PREMIUM(0xEE),
    USER_DAMAGE_SKIN_SAVE_REQUEST(0xF0),
    USER_DEFAULT_WING_ITEM(0xF1),
    USER_KAISER_TRANSFORM_WING(0xF2),
    USER_KAISER_TRANSFORM_TAIL(0xF3),
    USER_UPGRADE_TOMB_EFFECT(0xF4),
    USER_H_P(0xF5),
    PREMIUM(0xF6),
    USER_SELECT_NPC(0xF7),
    USER_SCRIPT_MESSAGE_ANSWER(0xF8),
    USER_SHOP_REQUEST(0xF9),
    TRUNK_OPERATION(0xFA),
    USER_ENTRUSTED_SHOP_REQUEST(0xFB),
    EXPRESS_REQUEST(0xFC),
    USER_EFFECT_LOCAL(0xFD),
    USER_SPECIAL_EFFECT_LOCAL(0xFE),
    USER_CREATE_AREA_DOT_REQUEST(0xFF),
    USER_CREATE_HOLIDOM_REQUEST(0x100),
    REQ_MAKING_SKILL_EFF(0x101),
    SHOP_SCANNER_REQUEST(0x102),
    SHOP_LINK_REQUEST(0x103),
    AUCTION_REQUEST(0x104),
    EXIT_AUCTION(0x105),
    ADMIN_SHOP_REQUEST(0x106),
    USER_GATHER_ITEM_REQUEST(0x107),
    USER_SORT_ITEM_REQUEST(0x108),
    USER_CHANGE_SLOT_POSITION_REQUEST(0x109),
    USER_TEXT_EQUIP_INFO(0x10A),
    USER_POP_OR_PUSH_BAG_ITEM_TO_INVENTORY(0x10B),
    USER_CHANGE_BAG_SLOT_POSITION_REQUEST(0x10C), //todo
    USER_POUR_IN_BAG_TO_BAG(0x10D),
    USER_STAT_CHANGE_ITEM_USE_REQUEST(0x10E),
    USER_STAT_CHANGE_ITEM_CANCEL_REQUEST(0x10F),
    USER_STAT_CHANGE_BY_PORTABLE_CHAIR_REQUEST(0x110),
    USER_MOB_SUMMON_ITEM_USE_REQUEST(0x111),
    USER_PET_FOOD_ITEM_USE_REQUEST(0x112),
    USER_TAMING_MOB_FOOD_ITEM_USE_REQUEST(0x113),
    USER_SCRIPT_ITEM_USE_REQUEST(0x114),
    USER_RECIPE_OPEN_ITEM_USE_REQUEST(0x115),
    USER_CONSUME_CASH_ITEM_USE_REQUEST(0x116),
    USER_ADDITIONAL_SLOT_EXTEND_ITEM_USE_REQUEST(0x117),
    USER_CASH_PET_PICK_UP_ON_OFF_REQUEST(0x118),
    USER_CASH_PET_SKILL_SETTING_REQUEST(0x119),
    USER_OPTION_CHANGE_REQUEST(0x11A),
    USER_DESTROY_PET_ITEM_REQUEST(0x11B),
    USER_BRIDLE_ITEM_USE_REQUEST(0x11C),
    USER_SKILL_LEARN_ITEM_USE_REQUEST(0x11D),
    USER_SKILL_RESET_ITEM_USE_REQUEST(0x11E),
    USER_ABILITY_RESET_ITEM_USE_REQUEST(0x11F),
    USER_ABILITY_CHANGE_ITEM_USE_REQUEST(0x120),
    USER_EXP_ITEM_GET_REQUEST(0x121),
    USER_CHAR_SLOT_INC_ITEM_USE_REQUEST(0x122),
    USER_CHAR_RENAME_ITEM_USE_REQUEST(0x123),
    USER_KAISER_COLOR_CHANGE_ITEM_USE_REQUEST(0x124),
    USER_SHOP_SCANNER_ITEM_USE_REQUEST(0x125),
    USER_MAP_TRANSFER_ITEM_USE_REQUEST(0x126),
    USER_PORTAL_SCROLL_USE_REQUEST(0x127),
    USER_FIELD_TRANSFER_REQUEST(0x128),
    USER_UPGRADE_ITEM_USE_REQUEST(0x129),
    USER_UPGRADE_ASSIST_ITEM_USE_REQUEST(0x12A),
    USER_HYPER_UPGRADE_ITEM_USE_REQUEST(0x12B),
    USER_FLAME_ITEM_USE_REQUEST(0x12C),
    USER_KARMA_CONSUME_ITEM_USE_REQUEST(0x13D),
    USER_EVENT_UPGRADE_ITEM_USE_REQUEST(0x13E),
    //12F
    //130
    USER_ITEM_OPTION_UPGRADE_ITEM_USE_REQUEST(0x131),
    USER_ADDITIONAL_OPT_UPGRADE_ITEM_USE_REQUEST(0x132),
    USER_ITEM_SLOT_EXTEND_ITEM_USE_REQUEST(0x133),
    USER_WEAPON_TEMP_ITEM_OPTION_REQUEST(0x134),
    USER_ITEM_SKILL_SOCKET_UPGRADE_ITEM_USE_REQUEST(0x135),
    USER_ITEM_SKILL_OPTION_UPGRADE_ITEM_USE_REQUEST(0x136),
    USER_FREE_MIRACLE_CUBE_ITEM_USE_REQUEST(0x137),
    USER_EQUIPMENT_ENCHANT_WITH_SINGLE_UI_REQUEST(0x138),
    EQUIP_ENCHANT_REQUEST(0x139),
    //
    //
    USER_ARC_ENHANCING_REQUEST(0x13C),
    USER_UI_OPEN_ITEM_USE_REQUEST(0x13D),
    USER_BAG_ITEM_USE_REQUEST(0x13E),
    USER_ITEM_RELEASE_REQUEST(0x13F),
    USER_MEMORIAL_CUBE_OPTION_REQUEST(0x140),
    USER_MIRACLE_CIRCULATOR_SELECT(0x141),
    USER_USE_NAVI_FLYING_SKILL_REQUEST(0x142),
    TOAD_HAMMER_REQUEST(0x143),
    USER_TOADS_HAMMER_HELP_REQUEST(0x144),
    //
    USER_CHANGE_SOUL_COLLECTION_REQUEST(0x146),
    USER_SELECT_SOUL_SKILL_UP_REQUEST(0x147),
    USER_ABILITY_UP_REQUEST(0x148),
    USER_ABILITY_MASS_UP_REQUEST(0x149),
    USER_DOT_HEAL(0X14A),
    CHANGE_STAT_REQUEST(0x14B),
    USER_CHANGE_STAT_REQUEST_BY_ITEM_OPTION(0x14C),
    //
    REMOVE_SON_OF_LINKED_SKILL_REQUEST(0x14E),
    SET_SON_OF_LINKED_SKILL_REQUEST(0x14F),
    USER_SKILL_UP_REQUEST(0x150),
    USER_SKILL_USE_REQUEST(0x151),
    //
    USER_SKILL_CANCEL_REQUEST(0x153),
    //
    USER_SKILL_PREPARE_REQUEST(0x155),
    //
    //
    //
    USER_ADD_FAME_REQUEST(0x159),
    //
    USER_PARTY_REQUEST(0x15B),
    CHAR_INFO_REQUEST(0x15C),
    USER_ACTIVATE_PET_REQUEST(0x15D),
    USER_REGISTER_PET_AUTO_BUFF_REQUEST(0x15E),
    USER_TEMPORARY_STAT_UPDATE_REQUEST(0x15F),
    USER_PORTAL_SCRIPT_REQUEST(0x160),
    USER_PORTAL_TELEPORT_REQUEST(0x161),
    USER_CALLING_TELEPORT_REQUEST(0x164), //checked
    TELEPORT_AURA(0x163),
    USER_ANTI_MACRO_ITEM_USE_REQUEST(0x164),
    USER_ANTI_MACRO_SKILL_USE_REQUEST(0x165),
    USER_OLD_ANTI_MACRO_QUESTION_RESULT(0x166),
    USER_ANTI_MACRO_REFRESH_REQUEST(0x167),
    USER_CLAIM_REQUEST(0x168),
    USER_QUEST_REQUEST(0x169),
    USER_MEDAL_REISSUE_REQUEST(0x16A),
    USER_CALC_DAMAGE_STAT_SET_REQUEST(0x16B),
    USER_B2_BODY_REQUEST(0x16C),
    USER_THROW_GRENADE(0x16D),
    USER_DESTROY_GRENADE(0x16E),
    USER_CREATE_AURA_BY_GRENADE(0x16F),
    USER_SET_MOVE_GRENADE(0x170),
    USER_MACRO_SYS_DATA_MODIFIED(0x171),
    USER_LOTTERY_ITEM_USE_REQUEST(0x173),
    USER_ROULETTE_START_REQUEST(0x174),
    USER_ROULETTE_RESULT_REQUEST(0x175),
    USER_ITEM_MAKE_REQUEST(0x176),
    USER_REPAIR_DURABILITY_ALL(0x177),
    USER_REPAIR_DURABILITY(0x178),
    USER_QUEST_RECORD_SET_STATE(0x179),
    USER_CLIENT_RESOLUTION_RESULT(0x17A),
    USER_FOLLOW_CHARACTER_REQUEST(0x17B),
    USER_FOLLOW_CHARACTER_WITHDRAW(0x17C),
    USER_SELECT_PQ_REWARD(0x17D),
    USER_REQUEST_PQ_REWARD(0x17E),
    SET_PASSENSER_RESULT(0x17F),
    USER_REQUEST_INSTANCE_TABLE(0x180),

    USER_REQUEST_CHARACTER_POTENTIAL_SKILL_RAND_SET_UI(0X193),
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    GROUP_MESSAGE(0x1AD),
    //
    //
    WHISPER(0x1B0),
    MESSENGER(0x1B1),
    MINI_ROOM_MULTI(0x1B2),
    MINI_ROOM_DUAL(0x1B3),
    UNK_1B4(0x1B4),
    PARTY_REQUEST(0x1B5),
    PARTY_RESULT(0x1B6),
    PARTY_INVITABLE_SET(0x1B7),
    EXPEDITION_REQUEST(0x1B8),
    PARTY_ADVER_REQUEST(0x1B9),
    URUS_PARTY_REQUEST(0x1BA),
    GUILD_REQUEST(0x1BB),
    GUILD_RESULT(0x1BC),
    GUILD_JOIN_REQUEST(0x1BD),
    GUILD_JOIN_CANCEL_REQUEST(0x1BE),
    GUILD_JOIN_ACCEPT(0x1BF),
    GUILD_JOIN_REJECT(0x1C0),
    GUILD_RANK_REQUEST(0x1C1),
    TOWER_RANK_REQUEST(0x1C2),


    SYSTEM_OPTION(0x1C7),
    //
    FRIEND_REQUEST(0x1C9),
    //
    WHAT_THIS(0x1CB),
    MAPLE_NOTES_REQUEST(0x1CC),


    CHANGE_KEYMAP(0x1D3),

    DODGE(0x1EF),// skillId  + tick 闪避


    USER_HYPER_SKILL_UP_REQUEST(0x207),
    USER_HYPER_SKILL_RESET_REQUEST(0x208),
    USER_HYPER_STAT_UP_REQUEST(0x209),
    USER_HYPER_STAT_RESET_REQUEST(0x20A),
    //
    //
    //
    //
    //
    //
    USER_REQUEST_CHANGE_MOB_ZONE_STATE(0x211),
    //
    //
    //
    //
    //
    //
    //
    CHANGE_CHAR_REQUEST(0x219),
    //
    CHECK_TRICK_OR_TREAT_REQUEST(0x21B),
    //
    //
    //
    USER_HOWLING_STORM_STACK(0x22B),
    //
    //
    ANDROID_SHOP_REQUEST(0x22E),
    COMBO_KILL_CHECK(0x231),
    EVENT_LIST_REQUEST(0x23A),
    USER_SOUL_EFFECT_REQUEST(0x247),
    FAMILIAR(0x249),
    STACK_CHAIRS(0x24F),
    MONSTER_COLLECTION(0x251),
    LEGION_LOAD_REQUEST(0x253),


    MATRIX_REQUEST(0x264),
    MATRIX_HELP_REQUEST(0x265),
    ARK_POWER(0x268), //int:能量数值
    和怪物相关(0x273),
    LIE_DETECTOR_TEST(0x274),

    USER_AVATAR_MODIFY_COUPON_USE_REQUEST(0x27B),
    //27C
    PET_MOVE(0x27D),
    PET_ACTION_SPEAK(0x27E),
    PET_INTERACTION_REQUEST(0x27F),
    PET_DROP_PICK_UP_REQUEST(0x280),
    PET_STAT_CHANGE_ITEM_USE_REQUEST(0x281),
    PET_UPDATE_EXCEPTION_LIST(0x282),
    PET_FOOD_ITEM_USE_REQUEST(0x283),
    PET_OPEN_SHOP(0x284),
    //
    //
    SKILL_PET_MOVE(0x287),//阴阳师-小白移动?
    SKILL_PET_ACTION(0x288),
    SKILL_PET_STATE(0x289),
    SKILL_PET_DROP_PICK_UP_REQUEST(0x28A),
    SKILL_PET_UPDATE_EXCEPTION_LIST_REQUEST(0x28B),
    //
    //
    SUMMON_MOVE(0x28E),
    SUMMON_ATTACK(0x28F),
    SUMMON_HIT(0x290),
    SUMMON_SKILL(0x291),
    SUMMON_REMOVE(0x292),
    SUMMON_ATTACK_PVP(0x293),
    SUMMON_ACTION(0x294),
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    ANDROID_MOVE(0x2A4),
    ANDROID_ACTION_SET(0x2A5),
    //
    //
    //
    //
    //
    CHANGE_QUICKSLOT(0x2AB),
    AFTER_INV_OP(0x2AC), //C9 07 00 00 | tick : C4 2D 68 01 | 00 00 15 00 00 00
    //
    //
    //
    //
    //
    //
    CHECK_PROCESS(0x2B3),
    //
    //
    //
    //
    SEND_MAPLE_NOTES(0x2B4),


    REQUEST_ARROW_PLATTER_OBJ(0x2C3),

    OPEN_UI(0x2DC), //各种界面开启的 HOOK
    TRANSFER(0x2E2),
    ORBITAL_FLAME(0x309),

    TICK_CHECK(0x324),
    UPDATE_TICK(0x333),


    DAILY_GIFT_CHECK_IN(0x33B),
    //
    //
    SKILL_COMMAND_LOCK(0x33E),
    //
    //
    //
    //
    //
    //
    //
    UNITY_PORTAL_REQUEST(0x346),
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    ENERGY_STORAGE_SKILL(0x354),

    ACHIEVEMENT(0x364),

    INCREASE_SKILL(0x36E), //无我之境 00 00 00 00 02 B6 C4 04

    OPEN_OR_CLOSE_UI(0x391),
    SKILL_COOL_IN_TEN_SECOND(0x393), //有啥用呢
    //
    BATTLE_MAGE_(0x395),


    POTION_POT_USE_REQUEST(0x3B5),
    POTION_POT_ADD_REQUEST(0x3B6),
    POTION_POT_OPTION_SET_REQUEST(0x3B7),
    POTION_POT_INC_REQUEST(0x3B8),
    HEXAGONAL_CUBE_MODIFIED(0x3C5),
    UNIQUE_CUBE_MODIFIED(0x3C6),
    USER_OPEN_MYSTERY_EGG(0x3DF),//
    OPEN_WORLD_MAP(0x3F6),

    MOB_MOVE(0x422),
    MOB_APPLY_CTRL(0x423),
    //
    //
    //
    //
    //
    //
    //
    MOB_ATTACK_MOB(0x42B),
    MOB_SKILL_DELAY_END(0x42C),
    MOB_TIME_BOMB_END(0x42D),
    MOB_ESCORT_COLLISION(0x42E),
    MOB_REQUEST_ESCORT_INFO(0x42F),
    MOB_ESCORT_STOP_END_REQUEST(0x430), //

    NPC_ANIMATION(0x443), //44A - 7
    SET_REACTOR_STATUS(0x44C),
    PICK_UP_ITEM(0x450),
    //
    //
    REACTOR_HIT(0x453),
    REACTOR_CLICK(0x454), //res 589 25 A1 07 00 01 77 04 2F FF 00 00 00 00 00 00 00 00 00 00 00
    REACTOR_RECT_IN_MOB(0x455),
    REACTOR_KEY(0x456),

    REQUEST_RECOMMEND_PLAYERS(0x481),
    //
    REQUEST_RECOMMEND_PARTIES(0x483),
    //
    //
    //
    REQUEST_RECOMMEND_CHAT_PLAYERS(0x487),
    //
    //
    //
    //
    //
    //
    QUICK_MOVE_SELECT(0x48E),
    //
    //
    //
    //
    OBSTACLE_ATOM_COLLISION(0x493),

    CASH_SHOP_POINT_REQUEST(0x5B7),
    CASH_SHOP_CASH_ITEM_REQUEST(0x5B8),
    //
    //
    //
    //
    CASH_SHOP_SAVE_COLLOCATION(0x5BD),

    GOLD_HAMMER_COMPLETE(0x5DB),

    BATTLE_ANALYSIS(0x5E0),
    //
    //
    //
    //
    //
    //
    //
    //
    UNK5E9(0x5E9), //01 00 00 00 00 00 00 00 01

    BEAST_TAMER_HIDE_EAR(0x5E7),

    PINK_BEEN_KNOCK_KNOCK(0x5FE),
    PINK_BEEN_KNOCK_DONE(0x5FF),
    EQUIP_EFFECT_OPT(0x60A),
    UNK614(0x614),

    END(0xA7F);

    private final int code;

    RecvOpcode(int code) {
        this.code = code;
    }

    public int getValue() {
        return code;
    }

    public static RecvOpcode getOpcode(int op) {
        for (RecvOpcode inHeader : RecvOpcode.values()) {
            if (inHeader.getValue() == op) {
                return inHeader;
            }
        }
        return null;
    }

}
